name: Build and Deploy Node.js App to Azure Web App - foodiee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install and build frontend
      - name: Install and build frontend
        working-directory: frontend-react
        run: |
          npm install
          npx update-browserslist-db@latest --force
          export CI=false
          npm run build

      # Step 4: Copy React build files to backend public folder
      - name: Copy React build to backend
        run: |
          cp -r frontend-react/build/* backend-socket.io/public/

      # Step 5: Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend-socket.io
          npm install

      # Step 6: Zip the backend for deployment
      - name: Zip backend for deployment
        run: |
          cd backend-socket.io
          zip -r ../release.zip ./*

      # Step 7: Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

    deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Step 8: Download the artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 9: Unzip the artifact for deployment
      - name: Unzip artifact
        run: unzip release.zip

      # Step 10: Login to Azure using the publish profile
      - name: Azure Login
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      # Step 11: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'foodiee'
          slot-name: 'Production'
          package: .
